# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3c3d5d37ee347d47e747e40a59d832ff4382a67487774f4138336c8def00e3a2b647744eb05824f965e43cc614f9d58e98ff4587492dbd9a83eb300fe3cf46e

test:
  secret_key_base: 250f2e8a6e73e8887f02b0352906145a551e2812e600e132cc12cb73280336c8c4e585730b61566b8f17ab2224e652484601ae49516aa80403b93d60ea9533a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
